Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Load Gtau
# Gtau = np.loadtxt("Gtau.in", skiprows=2)[:, 2]
Gtau = np.loadtxt("Gtau.in")[:, 2]

# Set imaginary-time
beta=100
ntau = len(Gtau)
ts = np.linspace(0.0, beta, ntau)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/var/folders/1t/fxgqx0n17z33mplwpw4n1d8r0000gn/T/ipykernel_58016/782615256.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m#Load Gtau[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;31m# Gtau = np.loadtxt("Gtau.in", skiprows=2)[:, 2][0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mGtau[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mloadtxt[0m[0;34m([0m[0;34m"Gtau.in"[0m[0;34m)[0m[0;34m[[0m[0;34m:[0m[0;34m,[0m [0;36m2[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0;31m# Set imaginary-time[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/homebrew/lib/python3.9/site-packages/numpy/lib/npyio.py[0m in [0;36mloadtxt[0;34m(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows, like)[0m
[1;32m   1040[0m             [0mfname[0m [0;34m=[0m [0mos_fspath[0m[0;34m([0m[0mfname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1041[0m         [0;32mif[0m [0m_is_string_like[0m[0;34m([0m[0mfname[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1042[0;31m             [0mfh[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mlib[0m[0;34m.[0m[0m_datasource[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mfname[0m[0;34m,[0m [0;34m'rt'[0m[0;34m,[0m [0mencoding[0m[0;34m=[0m[0mencoding[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1043[0m             [0mfencoding[0m [0;34m=[0m [0mgetattr[0m[0;34m([0m[0mfh[0m[0;34m,[0m [0;34m'encoding'[0m[0;34m,[0m [0;34m'latin1'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1044[0m             [0mline_iter[0m [0;34m=[0m [0miter[0m[0;34m([0m[0mfh[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/homebrew/lib/python3.9/site-packages/numpy/lib/_datasource.py[0m in [0;36mopen[0;34m(path, mode, destpath, encoding, newline)[0m
[1;32m    191[0m [0;34m[0m[0m
[1;32m    192[0m     [0mds[0m [0;34m=[0m [0mDataSource[0m[0;34m([0m[0mdestpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 193[0;31m     [0;32mreturn[0m [0mds[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mpath[0m[0;34m,[0m [0mmode[0m[0;34m,[0m [0mencoding[0m[0;34m=[0m[0mencoding[0m[0;34m,[0m [0mnewline[0m[0;34m=[0m[0mnewline[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    194[0m [0;34m[0m[0m
[1;32m    195[0m [0;34m[0m[0m

[0;32m/opt/homebrew/lib/python3.9/site-packages/numpy/lib/_datasource.py[0m in [0;36mopen[0;34m(self, path, mode, encoding, newline)[0m
[1;32m    530[0m                                       encoding=encoding, newline=newline)
[1;32m    531[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 532[0;31m             [0;32mraise[0m [0mFileNotFoundError[0m[0;34m([0m[0;34mf"{path} not found."[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    533[0m [0;34m[0m[0m
[1;32m    534[0m [0;34m[0m[0m

[0;31mFileNotFoundError[0m: Gtau.in not found.
FileNotFoundError: Gtau.in not found.

